packages:
  - packages/*
catalog:
  '@antfu/eslint-config': ^3.7.1
  '@antv/layout': ^0.3.25
  '@commitlint/cli': ^19.5.0
  '@commitlint/config-conventional': ^19.5.0
  '@dcloudio/types': ^3.4.12
  '@element-plus/icons-vue': ^2.3.1
  '@guolao/vue-monaco-editor': ^1.5.4
  '@iconify-json/ep': ^1.2.0
  '@iconify/types': ^2.0.0
  '@iconify/vue': ^4.1.2
  '@logicflow/core': ^2.0.5
  '@logicflow/extension': ^2.0.9
  '@smallwei/avue': ^3.5.1
  '@types/file-saver': ^2.0.7
  '@types/fs-extra': ^11.0.4
  '@types/lodash': ^4.17.9
  '@types/lodash-es': ^4.17.12
  '@types/node': ^22.7.0
  '@vue/test-utils': ^2.4.6
  '@vue/tsconfig': ^0.5.1
  '@vueuse/core': ^11.1.0
  acorn: ^8.12.1
  astring: ^1.9.0
  axios: ^1.7.7
  bumpp: ^9.5.2
  conventional-changelog-cli: ^5.0.0
  dagre: ^0.8.5
  dayjs: ^1.11.13
  defu: ^6.1.4
  element-plus: ^2.8.3
  eslint: ^9.11.1
  eslint-plugin-format: ^0.1.2
  file-saver: ^2.0.5
  fs-extra: ^11.2.0
  husky: ^9.1.6
  jsdom: ^25.0.1
  json5: ^2.2.3
  lint-staged: ^15.2.10
  lodash-es: ^4.17.21
  mitt: ^3.0.1
  monaco-editor: ^0.52.0
  rollup-plugin-scss: ^4.0.0
  sass: ^1.79.3
  simple-git-hooks: ^2.11.1
  taze: ^0.16.9
  tsc-alias: ^1.8.10
  tsx: ^4.19.1
  typescript: ^5.6.2
  unbuild: ^2.0.0
  unplugin-vue: ^5.1.5
  uview-plus: ^3.3.34
  vite: ^5.4.7
  vite-plugin-inspect: ^0.8.7
  vitepress: ^1.3.4
  vitest: ^2.1.1
  vue: ^3.5.8
  vue-request: ^2.0.4
  vue-router: ^4.4.5
  vue-tsc: 2.0.26
  vuedraggable: ^4.1.0
