packages:
  - packages/*
  - playground/*
catalog:
  '@antfu/eslint-config': ^3.14.0
  '@antv/layout': ^0.3.25
  '@commitlint/cli': ^19.6.1
  '@commitlint/config-conventional': ^19.6.0
  '@dcloudio/types': ^3.4.14
  '@dcloudio/uni-app': 3.0.0-alpha-4040520250107001
  '@dcloudio/uni-app-plus': 3.0.0-alpha-4040520250107001
  '@dcloudio/uni-h5': 3.0.0-alpha-4040520250107001
  '@dcloudio/uni-mp-weixin': 3.0.0-alpha-4040520250107001
  '@dcloudio/vite-plugin-uni': 3.0.0-alpha-4040520250107001
  '@element-plus/icons-vue': ^2.3.1
  '@guolao/vue-monaco-editor': ^1.5.4
  '@iconify-json/ep': ^1.2.2
  '@iconify/types': ^2.0.0
  '@iconify/vue': ^4.3.0
  '@logicflow/core': ^2.0.10
  '@logicflow/extension': ^2.0.14
  '@smallwei/avue': ^3.6.1
  '@types/file-saver': ^2.0.7
  '@types/fs-extra': ^11.0.4
  '@types/lodash': ^4.17.14
  '@types/lodash-es': ^4.17.12
  '@types/node': ^22.10.5
  '@vue/test-utils': ^2.4.6
  '@vue/tsconfig': ^0.7.0
  '@vueuse/core': ^12.4.0
  acorn: ^8.14.0
  astring: ^1.9.0
  axios: ^1.7.9
  bumpp: ^9.10.0
  conventional-changelog-cli: ^5.0.0
  dagre: ^0.8.5
  dayjs: ^1.11.13
  defu: ^6.1.4
  element-plus: ^2.9.3
  eslint: ^9.18.0
  eslint-plugin-format: ^1.0.1
  file-saver: ^2.0.5
  flatted: ^3.3.2
  fs-extra: ^11.2.0
  husky: ^9.1.7
  jsdom: ^26.0.0
  json5: ^2.2.3
  lint-staged: ^15.3.0
  lodash-es: ^4.17.21
  mitt: ^3.0.1
  monaco-editor: ^0.52.2
  rollup-plugin-scss: ^4.0.1
  sass: ^1.83.1
  simple-git-hooks: ^2.11.1
  taze: ^0.18.0
  tsc-alias: ^1.8.10
  tsx: ^4.19.2
  typescript: ^5.7.3
  unbuild: ^3.3.0
  unplugin-vue: ^5.2.1
  uview-plus: ^3.3.62
  vite: ^6.0.7
  vite-plugin-inspect: ^0.8.7
  vitepress: ^1.5.0
  vitest: ^2.1.8
  vixt: ^0.1.29
  vue: ^3.5.13
  vue-request: ^2.0.4
  vue-router: ^4.5.0
  vue-tsc: 2.0.26
  vuedraggable: ^4.1.0
